# noqa
"""Init

Revision ID: 4e7672b51420
Revises: 
Create Date: 2024-12-06 00:40:37.600605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e7672b51420'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('is_subscriber', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('language_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_tg_id'), 'user', ['tg_id'], unique=False)
    op.create_table('torrent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hash', sa.String(length=65), nullable=True),
    sa.Column('magnet_link', sa.Text(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_task_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_task_failed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('task_sent_at', sa.DateTime(), nullable=True),
    sa.Column('is_processing', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_bad', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_torrent_hash', 'torrent', ['hash'], unique=False, postgresql_using='hash')
    op.create_index(op.f('ix_torrent_id'), 'torrent', ['id'], unique=False)
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('save_path', sa.Text(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_hash_md5', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrent.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_content_hash', 'content', ['file_hash_md5'], unique=False, postgresql_using='hash')
    op.create_index(op.f('ix_content_id'), 'content', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_content_id'), table_name='content')
    op.drop_index('idx_hash', table_name='content', postgresql_using='hash')
    op.drop_table('content')
    op.drop_index(op.f('ix_torrent_id'), table_name='torrent')
    op.drop_index('idx_hash', table_name='torrent', postgresql_using='hash')
    op.drop_table('torrent')
    op.drop_index(op.f('ix_user_tg_id'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
