"""Many-to-many rel

Revision ID: bd29465f2e13
Revises: 4e7672b51420
Create Date: 2024-12-08 13:28:13.226495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd29465f2e13'
down_revision: Union[str, None] = '4e7672b51420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrent_content',
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrent.id'], ),
    sa.PrimaryKeyConstraint('torrent_id', 'content_id')
    )
    op.create_table('user_torrent',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('torrent_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrent.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'torrent_id')
    )
    op.add_column('content', sa.Column('ready', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.alter_column('content', 'save_path',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('content', 'file_hash_md5',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('content', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.drop_constraint('content_torrent_id_fkey', 'content', type_='foreignkey')
    op.drop_column('content', 'torrent_id')
    op.add_column('torrent', sa.Column('title', sa.String(length=255), nullable=False))
    op.alter_column('torrent', 'magnet_link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('torrent', 'size',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               nullable=False)
    op.drop_constraint('torrent_user_id_fkey', 'torrent', type_='foreignkey')
    op.drop_column('torrent', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('torrent', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('torrent_user_id_fkey', 'torrent', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('torrent', 'size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               nullable=True)
    op.alter_column('torrent', 'magnet_link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('torrent', 'title')
    op.add_column('content', sa.Column('torrent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('content_torrent_id_fkey', 'content', 'torrent', ['torrent_id'], ['id'], ondelete='CASCADE')
    op.alter_column('content', 'size',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('content', 'file_hash_md5',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.alter_column('content', 'save_path',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('content', 'ready')
    op.drop_table('user_torrent')
    op.drop_table('torrent_content')
    # ### end Alembic commands ###
