"""Changed torrent-content relation

Revision ID: 0bb054c1af99
Revises: bd29465f2e13
Create Date: 2024-12-12 21:09:48.816880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bb054c1af99'
down_revision: Union[str, None] = 'bd29465f2e13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('torrent_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'content', 'torrent', ['torrent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'content', type_='foreignkey')
    op.drop_column('content', 'torrent_id')
    # ### end Alembic commands ###
