"""Added user-content many-to-many rel

Revision ID: 83ce0b3d008a
Revises: 0bb054c1af99
Create Date: 2024-12-13 20:45:38.665167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ce0b3d008a'
down_revision: Union[str, None] = '0bb054c1af99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_content',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    op.drop_table('torrent_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrent_content',
    sa.Column('torrent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.id'], name='torrent_content_content_id_fkey'),
    sa.ForeignKeyConstraint(['torrent_id'], ['torrent.id'], name='torrent_content_torrent_id_fkey'),
    sa.PrimaryKeyConstraint('torrent_id', 'content_id', name='torrent_content_pkey')
    )
    op.drop_table('user_content')
    # ### end Alembic commands ###
