"""Added index field to Content

Revision ID: 646ef1e59b2c
Revises: 83ce0b3d008a
Create Date: 2024-12-13 21:02:47.952346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646ef1e59b2c'
down_revision: Union[str, None] = '83ce0b3d008a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'index')
    # ### end Alembic commands ###
