"""Remove Content attrs: is_deleted, file_hash_md5

Revision ID: ac4502808210
Revises: 3467f06af40f
Create Date: 2025-06-30 17:42:45.657489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac4502808210'
down_revision: Union[str, None] = '3467f06af40f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_content_hash', table_name='content', postgresql_using='hash')
    op.drop_column('content', 'file_hash_md5')
    op.drop_column('content', 'is_deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('is_deleted', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('content', sa.Column('file_hash_md5', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_index('idx_content_hash', 'content', ['file_hash_md5'], unique=False, postgresql_using='hash')
    # ### end Alembic commands ###
