"""Add is_unblocking_message_sent attr to User

Revision ID: 3467f06af40f
Revises: 588ce1da486f
Create Date: 2025-06-14 00:05:18.134766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3467f06af40f'
down_revision: Union[str, None] = '588ce1da486f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_unblocking_message_sent', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_unblocking_message_sent')
    # ### end Alembic commands ###
