"""Add User.is_blocked attr (default True).

Revision ID: 588ce1da486f
Revises: 7cba2cbe9196
Create Date: 2025-06-07 17:52:16.905219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '588ce1da486f'
down_revision: Union[str, None] = '7cba2cbe9196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_blocked', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_blocked')
    # ### end Alembic commands ###
